app/models/ticket.py
from sqlalchemy import Column, Integer, String
from app.extensions.db import Base

class Ticket(Base):
    __tablename__ = 'tickets'
    id = Column(Integer, primary_key=True,autoincrement=True)
    from_user = Column("from_user",String(50))
    text = Column('text',String(120), unique=False)
    role = Column('role',String(120), unique=False)
    status = Column('status',String(10), unique=False)

    def __init__(self,from_user=None,text=None, role=None,status=None):
        self.from_user = from_user
        self.text = text
        self.role = role
        self.status = status

    def __repr__(self):
        return f'<User {self.name!r}>'

app/models/user.py
from sqlalchemy import Column, Integer, String
from app.extensions.db import Base
from werkzeug.security import generate_password_hash, check_password_hash
class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, autoincrement=True,primary_key=True)
    username = Column(String(50), unique=True)
    password = Column(String(120), unique=False)
    role=Column(String(20), unique=False)

    def __init__(self, username=None, password=None,role=None):
        self.username = username
        self.password = generate_password_hash(password)
        self.role = role
        
    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f'<User {self.username!r}>'

app/__init__.py
from flask import Flask,render_template,session
#необхідно для server side sessions
from flask_session import Session
from os.path import join,isfile
from config import Config,basedir
from app.extensions import roles
from app.extensions import db
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    app.config['SESSION_PERMANENT'] = True
    app.config['SESSION_TYPE'] = 'filesystem'
    app.config["SESSION_REFRESH_EACH_REQUEST"] = False
    app.config['SESSION_FILE_THRESHOLD'] = 100  

    app.config['SECRET_KEY'] = Config.SECRET_KEY
    sess = Session()
    sess.init_app(app)
    
    db.init_db(Config.SQLALCHEMY_DATABASE_URI)
    
    if not isfile(join(basedir,"app.db")):
        from app.extensions.db import db_session,engine,Base
        from app.models.user import User
        from app.models.ticket import Ticket
        #val = Base.metadata.tables.values()
        Base.metadata.drop_all(bind=engine)
        Base.metadata.create_all(bind=engine)
        db_session.add(User("admin","admin","admin"))
        db_session.add(User("manager","manager","manager"))
        db_session.add(User("analyst","analyst","analyst"))
        db_session.add(User("user","user","user"))
        db_session.commit()

    from app.tickets import bp as tickets_bp
    app.register_blueprint(tickets_bp)
    from app.login import bp as login_bp
    app.register_blueprint(login_bp)
    from app.users import bp as users_bp
    app.register_blueprint(users_bp)
    
    @app.route('/')
    @roles.logged
    def index():
        return render_template("home.html")
        
    @app.before_request
    def make_session_permanent():
        session.permanent = True
        

    @app.teardown_appcontext
    def shutdown_session(exception=None):
        db.db_session.remove()
    return app

app/login/__init__.py
from flask import Blueprint

bp = Blueprint('login', __name__)

from app.login import routes

app/login/routes.py
from flask import render_template, redirect, url_for, request,session,flash
from app.login import bp
from app.models.user import User

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if "logged" in session:
        return redirect(url_for("index"))
    if request.method == 'POST':
        form = request.form
        form_user = form.get("username",False)
        form_pwd = form.get("password",False)
        if form_user and form_pwd:
            user = User.query.filter(User.username == form_user).first()
            if user and user.check_password(form_pwd):
                session["username"] = user.username
                session["logged"] = True
                session["role"] = user.role
                session.modified = True
                return redirect(url_for('index'))
        flash('Invalid Credentials. Please try again.', 'error')
    return render_template('login.html')


@bp.route('/logout', methods=['GET'])
def logout():
    session.clear()
    return redirect(url_for("login.login"))

app/tickets/__init__.py
from flask import Blueprint

bp = Blueprint('tickets', __name__)

from app.tickets import routes

app/tickets/routes.py
from flask import request, redirect, url_for,session,render_template,flash
from app.extensions.db import db_session
from app.tickets import bp
from app.extensions import roles
from app.models.ticket import Ticket

@bp.route('/tickets')
@roles.deny(groups=["user"])
def index():
    if session["role"] == "admin":
        tickets = Ticket.query.all()
    else:
        tickets = Ticket.query.filter(Ticket.role == session["role"])
    return render_template('tickets/list.html', tickets=tickets,role=session["role"])

@bp.route('/tickets/my')
@roles.allow(groups=["user"])
def user_tickets():
    tickets = Ticket.query.filter(Ticket.from_user == session["username"])
    return render_template('tickets/user_list.html', tickets=tickets,role=session["role"])

@bp.route('/tickets/assign',methods=["POST"])
@roles.allow(groups=["admin"])
def assign_ticket():

    ticket_id = request.form.get("id","")
    target = request.form.get("target","")
    ticket = Ticket.query.filter(Ticket.id == ticket_id).first()
    if ticket:
        ticket.role = target
        try:
            db_session.commit()
            flash("Success","success")
        except:
            flash("Error","error")
    else:
        flash("Success","success")
    return redirect(url_for("tickets.index"))


@bp.route('/tickets/status',methods=["POST"])
@roles.deny(groups=["user"])
def set_status():
    
    ticket_id = request.form.get("id","")
    status = request.form.get("status","")
    if session["role"] == "admin":
        ticket = Ticket.query.filter(Ticket.id == ticket_id).first()
    else:
        ticket = Ticket.query.filter(Ticket.id == ticket_id,Ticket.role == session["role"]).first()
    if ticket:
        ticket.status = status
        try:
            db_session.commit()
            flash("Success","success")
        except:
            flash("Error","error")
    else:
        flash("Ticket not found","error")
        
    return redirect(url_for("tickets.index"))

@bp.route('/tickets/create',methods=["GET","POST"])
@roles.allow(groups=["user"])
def create_ticket():
    error = None
    if request.form.get("submit_ticket",False) != False:
        form_target = request.form.get("target","")
        form_text = request.form.get("text","")
        ticket = Ticket(session["username"],form_text,form_target,"pending")
        try:
            db_session.add(ticket)
            db_session.commit()
            flash("Success","success")
        except:
            flash("Error","error")
    return render_template('tickets/create.html', error=error)

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import routes

app/users/routes.py
from flask import render_template,request,session,flash
from app.extensions.db import db_session
from app.users import bp
from app.extensions import roles
from app.models.user import User

@bp.route('/users',methods=["GET","POST"])
@roles.allow(groups=["admin"])
def index():
    if request.method == 'POST':
        if request.form.get("set_role",False) != False:
            form_user = request.form.get("username","")
            form_role = request.form.get("role","")
            user = User.query.filter_by(username=form_user).first()
            if user:
                user.role = form_role
                db_session.commit()
                if session["username"] == form_user:
                    session["role"] = form_role
                    session.modified = True
                flash("Success","success")
            else:
                flash("User not found","error")
    users = User.query.all()
    return render_template('users/list.html', users=users)

app/templates/home.html
{% extends "layout.html" %}
{% block title %}Home {% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block content %}
<main>
  {% if session["role"] == "admin" %}
    <p>Your role: {{ session["role"] }}</p>
    <ul>
      <li>
        <a href="{{ url_for("users.index") }}">Users management</a>
      </li>
      <li>
        <a href="{{ url_for("tickets.index") }}">Tickets management</a>
      </li>
    </ul>
  {% elif session["role"] == "manager" %}
    <p>Your role: {{ session["role"] }}</p>
    <ul>
      <li>
        <a href="{{ url_for("tickets.index") }}">View tickets</a>
      </li>
    </ul>
    {% elif session["role"] == "analyst" %}
    <p>Your role: {{ session["role"] }}</p>
    <ul>
      <li>
        <a href="{{ url_for("tickets.index") }}">View tickets</a>
      </li>
    </ul>
  {% elif session["role"] == "user" %}
    <p>Your role: {{ session["role"] }}</p>
    <ul>
      <li>
        <a href="{{ url_for("tickets.user_tickets") }}">My tickets</a>
      </li>
      <li>
        <a href="{{ url_for("tickets.create_ticket") }}">Create ticket</a>
      </li>
    </ul>
  {% endif %}
</main>
  {% endblock %}
 

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <title>{% block title %}{% endblock %} - Tickets</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
      .error {
        color:red;
      }
      .success {
        color:green;
      }
    </style>
  </head>
  <body>
    <div class="col-lg-8 mx-auto p-4 py-md-5">
      <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        <b class="me-3">{{session["username"]}} </b>
        <span>role: {{ session["role"] }}</span>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{{url_for("index")}}">Home</a>
          <a class="py-2 link-body-emphasis text-decoration-none" href="{{url_for("login.logout")}}">Logout</a>
        </nav>
      </header>
    {% block content %}{% endblock %}
  
    
  </div>
  </body>
</html>

app/templates/login.html
<html>
  <head>
    <title>login</title>
    <style>
      .error {
        color:red;
      }
      html,
body {
  height: 100%;
}

.form-signin {
  max-width: 330px;
  padding: 1rem;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    <main class="form-signin w-100 m-auto">
      <form method="POST">
        {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul class=flashes>
        {% for category, message in messages %}
          <li class="{{ category }}">{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}

        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating">
          <input id="floatingInput" class="form-control" type="text" placeholder="Username" name="username" />
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input id="floatingPassword" class="form-control" type="password" placeholder="Password" name="password" />
          <label for="floatingPassword">Password</label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
      </form>
    </main>
  </body>
</html> 

app/templates/tickets/create.html
{% extends "layout.html" %}
{% block title %}Create ticket {% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block content %}
<h2>create ticket</h2>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  <ul class=flashes>
  {% for category, message in messages %}
    <li class="{{ category }}">{{ message }}</li>
  {% endfor %}
  </ul>
{% endif %}
{% endwith %}
<form action="" method="post">
<textarea name="text" value="" placeholder="text" required></textarea>
<br><br>
<label for="role">target:</label>

<select name="target" required>

  <option value="admin">admin</option>
  <option value="manager">manager</option>
  <option value="analyst">analyst</option>

</select>
<br><br>
        <input  type="submit" name="submit_ticket" value="Send">
      </form>
{% endblock %}

app/templates/tickets/list.html
{% extends "layout.html" %}
{% block title %}Tickets{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<main>
  <h3>tickets</h3>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul class=flashes>
        {% for category, message in messages %}<li class="{{ category }}">{{ message }}</li>{% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
  <table class="table table-striped table-bordered">
    <tr>
      <th>from</th>
      <th>to</th>
      <th>text</th>
      <th>status</th>
      <th>new_status</th>
      {% if session["role"] == "admin" %}<th>assign</th>{% endif %}
    </tr>
    {% if tickets %}
      {% for ticket in tickets %}
        <tr>
          <td>{{ ticket.from_user }}</td>
          <td>{{ ticket.role }}</td>
          <td>{{ ticket.text }}</td>
          <td>{{ ticket.status }}</td>
          <td>
            
            <form class="row row-cols-lg-auto g-3 align-items-center" action="{{ url_for("tickets.set_status") }}" method="post">
              <input type="hidden" name="id" value="{{ ticket.id }}">
              <div class="col-12">
              <select class="form-select form-select-sm" name="status" required>
                <option value="pending">pending</option>
                <option value="review">in review</option>
                <option value="closed">closed</option>
              </select>
              </div>
              <div class="col-12">
              <button class="btn btn-sm btn-primary" type="submit">Set</button>
              </div>
            </form>
          </td>
          {% if session["role"] == "admin" %}
            <td>
              <form class="row row-cols-lg-auto g-3 align-items-center" action="{{ url_for("tickets.assign_ticket") }}" method="post">
                <input type="hidden" name="id" value="{{ ticket.id }}">
               <div class="col-12">
               <select class="form-select form-select-sm" name="target" required>
                  <option value="admin">admin</option>
                  <option value="manager">manager</option>
                  <option value="analyst">analyst</option>
                </select>
                </div>
<div class="col-12">
                <button class="btn btn-sm btn-primary" type="submit">Assign</button>
                </div>
              </form>
            </td>
          {% endif %}
        </tr>
        {{ card }}
      {% endfor %}
    {% endif %}
  </table>
  </main>
{% endblock %}

app/templates/tickets/user_list.html
{% extends "layout.html" %}
{% block title %}Tickets{% endblock %}
{% block head %}
  {{ super() }}
  <style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 50%;
  }

  td,
  th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 5px;
  }

  tr:nth-child(even) {
    background-color: #dddddd;
  }

  td form {
    display: table-row;
  }
  </style>
{% endblock %}
{% block content %}
  <h1>tickets</h1>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul class=flashes>
        {% for category, message in messages %}<li class="{{ category }}">{{ message }}</li>{% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
  <table>
    <tr>
      <th>from</th>
      <th>to</th>
      <th>text</th>
      <th>status</th>
    </tr>
    {% if tickets %}
      {% for ticket in tickets %}
        <tr>
          <td>{{ ticket.from_user }}</td>
          <td>{{ ticket.target }}</td>
          <td>{{ ticket.text }}</td>
          <td>{{ ticket.status }}</td>
        </tr>
      {% endfor %}
    {% endif %}
  </table>
{% endblock %}

app/templates/users/list.html
{% extends "layout.html" %}
{% block title %}Users{% endblock %}
{% block head %}
  {{ super() }}
  <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 300px;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 3px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
  </style>
{% endblock %}
{% block content %}
  <h3>user management</h3>
  <br>
  <table>
    <tr>
      <th>username</th>
      <th>role</th>
    </tr>
    {% if users %}
      {% for user in users %}
        <tr>
          <td>{{ user.username }}</td>
          <td>{{ user.role }}</td>
        </tr>
        {{ card }}
      {% endfor %}
    {% endif %}
  </table>
  <br>
  <h2>set role</h2>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul class=flashes>
        {% for category, message in messages %}<li class="{{ category }}">{{ message }}</li>{% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
  <form action="" method="post">
    <input type="text" placeholder="Username" name="username" value="" required>
    <label for="pet-select">role:</label>
    <select name="role" id="pet-select" required>
      <option value="admin">admin</option>
      <option value="manager">manager</option>
      <option value="analyst">analyst</option>
      <option value="user">user</option>
    </select>
    <input type="submit" name="set_role" value="Send">
  </form>
{% endblock %}